security:
    encoders:
        Study\BlogBundle\Entity\User : sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_EDITOR

    providers:
        user:
            entity:
              class: StudyBlogBundle:User
              property: username

    firewalls:
        backend:
            pattern: ^/.*
            provider: user
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /
            logout:
                path:   /logout
                target: /
                invalidate_session: false
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 3600
                path:     /
                domain:   ~
                remember_me_parameter: _remember_me

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/backend/user/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/post/add, roles: ROLE_EDITOR }
        - { path: ^/backend/post/edit/*, roles: ROLE_EDITOR }
        - { path: ^/admin, roles: ROLE_ADMIN }