study_add_blog:
    pattern:  /blog/add
    defaults: { _controller: StudyBlogBundle:Default:create }

study_edit_blog:
    pattern:  /blog/edit/{id}
    defaults: { _controller: StudyBlogBundle:Default:edit }

study_delete_blog:
    pattern:  /blog/delete/{id}
    defaults: { _controller: StudyBlogBundle:Default:delete }
    
study_home_blog:
    pattern:  /blog
    defaults: { _controller: StudyBlogBundle:Default:index }
