parameters:
#    study_blog.example.class: Study\BlogBundle\Example

services:
#    study_blog.example:
#        class: %study_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
