parameters:
    study_blog.log.class: Study\BlogBundle\Service\Log

services:
    study_blog_log:
        class: %study_blog.log.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    my.listener:
        class: Study\BlogBundle\EventListener\AddSlug
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    study.twig.study_extension:
        class: Study\BlogBundle\Twig\StudyExtension
        tags:
            - { name: twig.extension }